### ISSUE TITLE
Feature request: Toggle transparency

### ISSUE THREAD

**Issue by domadden** [lanoxx/tilda#103]
I think the biggest thing about a transparent terminal is you get extra screen space without having multiple monitors. You can read documentation without alt-tabing or minimizing all the time or read and type that really long command without switching between screens. But, you don't always need to do these things. There are times when the background is just a distraction. It would be really nice if I could just toggle off the transparency with a keybind and get to work!

**Comment by lanoxx** [comment]
Regarding commit pik@edf812b

I would prefer not to have tilda_window depend on wizard. I would rather move the code for changing transparancy to tilda_window and make the function public, then call it from wizard. That way you can also get rid of the duplicate code.

**Comment by pik** [comment]
@lanoxx 
I updated the code at #111, with toggle_transparency now in tilda_window. I will rebase of master, so its a single commit, probably after font-size shortcut gets pulled in. 

One small thing is that currently the transparency widget is non-sensitive when transparency is disabled https://github.com/pik/tilda/commit/5068f8994b4533381c7c0dbaf9cb4e0a59f210ea#diff-c4ad869bd8992074ff1fcadae1f1bd60R1282 - that's a little strange if you use transparency (but  have it toggled off while wizard is open, since you need to toggle it on to adjust it). It's not really important, but maybe it's a little awkward?
