### ISSUE TITLE
full screen shortcut

### ISSUE THREAD

**Issue by voidplayer** [lanoxx/tilda#11]
New toogle full screen option is awesome. How about a nice shorcut? ;)

**Comment by agitato816** [comment]
f11 shortcut works. but when i press f11, "~" appers in tilda. how to fix it?

i'm on ubuntu 14.04
fyi: i'm using tilda shortcut for f1, and guake for f12.

**Comment by lanoxx** [comment]
Hi, I believe this bug has already been fixed. Please check if you are using the lastest version of tilda.

**Comment by logenkain** [comment]
https://launchpad.net/ubuntu/trusty/+package/tilda

looks like they are using 1.1.11, unless I'm reading that wrong.  As of 14.04, the current tilda release was indeed 1.1.11.  You're either going to have to build it yourself, or use a more up to date distribution.

Apparently even 14.10 only uses 1.1.12 https://launchpad.net/ubuntu/utopic/+package/tilda which is still out of date, but I'm not sure when that bug was fixed.  You might be able to download the 1.1.12 version from launchpad.  I couldn't find any ubuntu packages that were completely up to date.

My recommendation is to simply compile it yourself.  I doubt tilda will have any dependency issues if you should choose to try a newer version and stick with 14.04.

Good luck.

**Comment by lanoxx** [comment]
Hi there,

the packaging situation is on Ubuntu is a little messed up, because ubuntu does not always sync the latest packages from Debian. I do not have the time to ask for a manual sync each time when I release an update, so Ubuntu always lags behind until the next release. You can try to download the latest version from Debian unstable which actually is 1.2.x, if I am not mistaken it should be compatible with Ubuntu.
