### ISSUE TITLE
Better identification of current tab

### ISSUE THREAD

**Issue by tandiljuan** [lanoxx/tilda#142]
I have recently started to use Tilda. And, so far, the only issue that I've found is the difficulty to identify the current tab (or when moving between tabs). I guess that a simple solution could be to underscore the text of the current selected tab.

Thanks and regards,
juan.

**Comment by arwer13** [comment]
+1, this is also the only issue I have now with Tilda.

**Comment by pik** [comment]
I opened an issue that's tangential to this here: https://github.com/lanoxx/tilda/issues/134 although in my opinion it really may be better left to the shell (idk about other shells but it's handled in fish quite well).

**Comment by lanoxx** [comment]
Sounds like a CSS issue to me. I am not sure if this is a tilda issue but we could probably update the integrated css rules to highlight the current tab.

**Comment by pik** [comment]
It's possible to do something like (in your gtk.css): 
```
.notebook tab:active {
    background-color: #FFFFFF;
}```

Tilda doesn't seem to have custom name-spaces for its classes which might be something to fix?

**Comment by lanoxx** [comment]
The tilda window actually has a name: "Main". 

See: https://github.com/lanoxx/tilda/blob/master/src/tilda.c#L715

**Comment by lanoxx** [comment]
I am closing this. Tilda just uses the default GtkNotebook which should have sufficient styling to distinguish the active tab from the other tabs. If for some reason this does not apply on your computer, then the most logical explanation would be that your theme overwrites the default style (GTK uses Adwaita). You can either try to change your theme or manually override the style of the tabs with something like this:

    .notebook tab:active {
        color: red;
    }

or 

    .notebook tab:active GtkLabel {
        color: red;
    }

On more recent systems its also possible to use GtkInspector in order to analyse the style of an application

**Comment by pik** [comment]
> tilda window actually has a name: "Main".

Maybe TildaMain would be better ?

**Comment by lanoxx** [comment]
This name is part of the public API of tilda, changing it would possibly cause other peoples stylesheets to become invalid, so I dont think we should change it. Anyway the style file is local to tilda and so the difference would be minimal, I think the main usecase it to be able to style the tilda window notebook separate from the wizard notebook.
