### ISSUE TITLE
Get a notify everytime command is executed

### ISSUE THREAD

**Issue by rajhundal7** [lanoxx/tilda#154]
Hi,

I just upgraded to Fedora 22 from Fedora 18 and now everytime I execute a command, I get a notify in the prompt as follows:

]777;notify;Command completed;ls -l[raj@fedora ~]$ cd /etc
]777;notify;Command completed;cd /etc[raj@fedora etc]$ 

I have removed and installed Tilda a couple of times and even tried to delete all tilda directories in the .config and .cache dirs. I do not think this is a Fedora issue as I ran into it on Debian also a while back but I cannot remember how it happened back then and I think the fix at that was to remove and re-install tilda though it does not seem to working this time.

**Comment by rajhundal7** [comment]
Forgot to mention this does not occur on regular terminal and I also installed Konsole and it does not happen there either.

**Comment by lanoxx** [comment]
There is no code inside tilda that would print something like this. I can only imagine that its due to some script that is implicitly run after each command. I recommend you check which shell is being started and if that shell (if not bash) has any configuration to print such a message after executing a command.

In bash a typical way to achieve such a thing is to set $PROMPT_COMMAND.

**Comment by lanoxx** [comment]
Here is some more information I just found: https://bugzilla.redhat.com/show_bug.cgi?id=1220006

**Comment by lanoxx** [comment]
I believe this was an issue that existed only on Fedora was already fixed there. If I am wrong and something really needs to be changed in tilda, then please reopen this issue.

**Comment by NickolasLapp** [comment]
In case someone comes across this later having the same problem (running fedora 22), the solution was to set the $PROMPT_COMMAND variable to something different in ~/.bashrc. Not a tilda issue, but a problem using gnome that is only displayed in tilda.

The issue is caused here: https://bugzilla.redhat.com/show_bug.cgi?id=1220006
And I found the solution here: https://www.reddit.com/r/Fedora/comments/37n9vi/vte/

**Comment by htonus** [comment]
comment the string as shown
> sudo vim /etc/profile.d/vte.sh
...
_vte_prompt_command() {
...
 #printf "\033]777;notify;Command completed;%s\007\033]0;%s@%s:%s\007%s" "${command}" "${USER}" "${HOSTNAME%%.*}" "${pwd}" "$(__vte_osc7)"
}

**Comment by kathan420** [comment]
I was also getting this kind of error
I fixed it by this 

> unset PROMPT_COMMAND

**Comment by Cloud-Of-Li** [comment]
you can fixed by input "unset PROMPT_COMMAND", but as far as I'm concerned, I think we can change something like PROMPT_COMMAND in the /etc/bashrc...
