### ISSUE TITLE
screen command causes Tilda to minimize, and sometimes wont' come back

### ISSUE THREAD

**Issue by bobloblian** [lanoxx/tilda#192]
Hi,

I sometimes like to run the screen command on a remote server so I can leave a bash instance running without killing it by disconnecting.  When I run the screen command in Tilda, it minimizes (as opposed to the pulldown/pullup it normally does).  Sometimes, if I repeatedly press the F12 key, Tilda will eventually pull down again, but just as often as not it is completely non-responsive and I am unable to get access to it again.  I can see the process remains running in ps using another terminal.

I am running ubuntu 14.04, perhaps this has been fixed and is not in the repositories, but I could find no mention of it in the issues reported...

Great program, by the way, kudos and thanks for making it available...

**Comment by lanoxx** [comment]
Hi,

well 14.04 comes with tilda 1.1.11, this is not only outdated (there was 1.1.13) but there has also been a new minor release for tilda 1.2, I will release tilda 1.3 probably this month. Chances are good that this was already fixed in a more recent release, if you know how to compile from this git repository then I recommend to just compile 1.2.4, it will work on Ubuntu 14.04, otherwise if you feel experimental you can also compile from git master.

**Comment by lanoxx** [comment]
> Great program, by the way, kudos and thanks for making it available...
Thanks your feedback is much appreciated :-)

P.S. Looking at the changes from 1.1.12 and 1.1.13 I don't think either of those fixed this, I don't think there is a way to get an update into Ubuntu 14.04 (especially not for 1.2.x) , so if you want a newer version you will need to build from source. Closing this, if you have access to a more recent version and this issue still happens to you, then feel free to reopen.
