### ISSUE TITLE
Control-Shift-W closes 2 tabs

### ISSUE THREAD

**Issue by dEvasEnApati** [lanoxx/tilda#232]
Dear Tilda developer

Thanks for this wonderful dropdown termnial.

I am using it on Lubuntu 16.04. Control-Shift-W closes 2 tabs the same time. When I remap 'Close tab' to Control-Shift-R, it works fine.

Please have a look

**Comment by pik** [comment]
Is there a chance this is related to your key-repeat rate-settings? It's possible for there to be a bug that triggers two tabs to close but it doesn't make a lot of sense to me that it would depend on the keybinding used per say.

**Comment by pik** [comment]
I seem to be able to replicate for any hot-keys after upgrading the following: gtk3.18 -> gtk3.20 / vte3 0.42.5-1 -> vte3-0.44.1-1.

**Comment by lanoxx** [comment]
Hi Alex,

I wish i had some more time at the moment to look at this. But unfortunately at the moment its rather difficult. But I want to clarify a few things in case you have a chance to look at this:

This bug is not related to key repeat speed. There seems to be a conflict in the way the callbacks for keybindings get registered. The context menu registeres a separate set of keybindings when its created. I tried to fix this by pushing a commit to tilda 1.3.2 but that has broken the close button completely. In my opinion the way forward is to rework how the hotkeys are registered. Unfortunately at the moment I have no quick idea how to fix this without spending a few more hours with the gtk documentation. I also dont quite understand why only the close button is affected.

**Comment by lanoxx** [comment]
Guess I should have looked at your pull request before replying, and it looks like I completely overlooked the return value of that callback as I was only looking at the way the callbacks were registered. Anyway, good job @pik for fixing this and thanks a lot.

**Comment by pik** [comment]
Well it still looks like we are actually registering the accelerators in two place's so it would be nice to clean this up in the code and not have doubled up signal listeners; but stopping event propagation seems to solve the bug for now.

**Comment by lanoxx** [comment]
Yes, but that would probably require a larger rework of the key-binding code, I am not sure thats worth the effort.

**Comment by kronos29296** [comment]
I have found the same bug in ubuntu 17.04. On remapping to Ctrl Shift R the bug disappears

**Comment by dimon2242** [comment]
@kronos29296, And you can just remove and add againg ctrl + shift + w combination, that fix it!)
