### ISSUE TITLE
tilda transparency problem on arch linux using gnome

### ISSUE THREAD

**Issue by ShinZ6** [lanoxx/tilda#269]
Tilda doesn't have transparency on startup. Using Arch Linux with GNOME as a desktop environment.
The following error was shown: 

(tilda:3042): Vte-CRITICAL **: void vte_terminal_set_colors(VteTerminal*, const GdkRGBA*, const GdkRGBA*, const GdkRGBA*, gsize): assertion 'background == nullptr || valid_color(background)' failed

**Comment by jorgicio** [comment]
The same happens here, using MATE in Gentoo.

**Comment by wonux** [comment]
The same happens here, using dwm in Gentoo,Arch.

**Comment by adam-23** [comment]
When using .xprofile in Arch w/Gnome and X to startup tilda with cava, it starts with a black background, even though config_0 is set to 80% transparent. Here's what I'm using in .xprofile:

    tilda &

Also, using another terminal like gnome-terminal or xfce4-terminal to open tilda still results in a black background (noted, the only issue is the background; it still loads at the correct size and other config settings, just not transparent at login). 
For example:

    gnome-terminal -e tilda &

**Comment by s0me-1** [comment]
Same error under Manjaro KDE 17

`(tilda:2547): Vte-CRITICAL **: void vte_terminal_set_colors(VteTerminal*, const GdkRGBA*, const GdkRGBA*, const GdkRGBA*, gsize): assertion 'background == nullptr || valid_color(background)' failed
`

**Comment by Yodzorah** [comment]
Manjaro+XFCE 17. The same.

**Comment by cgorgulla** [comment]
Same here again on Gentoo/Mate. But only with the latest 1.4 version which I have tried, the old version I had installed 1.1.12 worked well.

**Comment by victor-lund** [comment]
A dirty workaround is to set transparency to 99% instead of 100. Worked for me on Arch using tilda 1.5~alpha

**Comment by lanoxx** [comment]
I cannot reproduce the issue locally, but I found one place where an incorrect color value is computed and stored in the tilda configuration. It is possible that this is the cause of this error. In my case a negative value -65 was stored in the configuration when I set transparency to 100. I will fix this issue today.

Please have a look into the tilda config file and look for the value of `back_alpha` which stores the background alpha channel value as 16bit integer. The value should be between 0 and 65535. 0 means completely transparent and 65555 means completely opaque.

If you find a wrong value in the configuration, then please let me know if the problem is resolved if you close tilda, correct the value and start tilda again. Not that tilda writes the config on exit, so you cannot change it manually while tilda is running.

**Comment by Yodzorah** [comment]
@lanoxx, there is nothing wrong with `back_alpha` value for me, though I still have the bug.

>@victor-lund
>A dirty workaround is to set transparency to 99% instead of 100.

Doesn't work for me.

Btw, if it works correctly when you're setting up the value from preferences, after startup, but doesn't work on startup, then maybe we should check what's the difference between transparency setup on startup and from preferences. For example, I need to set up the value in preferences each time I launch Tilda, but after that it's ok until I launch another Tilda (not a tab).

**Comment by lanoxx** [comment]
It would be helpful to have a stacktrace. Could you by any chance run tilda with `G_DEBUG="fatal-criticals"` in GDB and try to get a stacktrace of the problem?

**Comment by Mihaion** [comment]
Thanks Victor-lund

**Comment by arbaes** [comment]
@lanoxx i'd like to provide you a stacktrace but I'm not sure what to do since I never used GDB before.

**Comment by eduardobeattie** [comment]
I solved this problem in KDE by having this as the startup command:
`until /usr/bin/qdbus org.kde.KWin; do sleep 0.5; done; /usr/bin/tilda`
This waits until the composer (KWin) is loaded and available before launching tilda, which makes transparency work on startup. Hopefully someone can adapt this to work for GNOME :)
