### ISSUE TITLE
tilda 1.3.3 crashed on Fedora running Wayland

### ISSUE THREAD

**Issue by valentt** [lanoxx/tilda#296]
I can't start tilda on Fedora running Gnome 3 dekstop via Wayland. If I switch back to Xorg then tilda works.

Have you tried running tilda on Wayland? Is this a know issue?

**Comment by valentt** [comment]
If tilda devs don't have time to make tilda work with wayland it there any good alternative to switch to that also has tabs and enough options (bottom not top) ?

**Comment by lanoxx** [comment]
The reason why tilda does not work on wayland is its hard dependency to X11, which are not present on Wayland.

There are two reasons why Tilda interfaces directly with wayland which is not easy to change:

1. To register a global hotkey in order to show and hide tilda
2. To control the view and hide animation.

I certainly to not have any time to change this in the near future. So for the time being Tilda is Xorg only.
