### ISSUE TITLE
tilda starts without proxy env variables set

### ISSUE THREAD

**Issue by cbruchert** [lanoxx/tilda#317]
I'm using Ubuntu 17.10 and need to access the Internet using a proxy server. When using alt-f2 or when adding it to the Startup Application tool, tilda starts bash without my proxy env variables (e.g.: http_proxy) making programs like wget or curl to get stuck for a long time before timing out. The same does not happen when starting gnome-terminal using alt-f2.

**Comment by egmontkob** [comment]
It is gnome-terminal itself that sets these variables based on some GNOME-wide (gsettings/dconf) settings. This feature is debated sometimes (see e.g. https://bugzilla.gnome.org/show_bug.cgi?id=747800, warning: it's flame-ish), gnome-terminal officially claims it does so because it is the _GNOME_ Terminal, hence sets _GNOME_'s settings.

Asking all other terminal emulators, e.g. `tilda` which probably isn't meant for the GNOME desktop in particular, to copy this behavior is probably not the right approach.

It could go out to one level (e.g. the entire GNOME desktop or whichever other desktop / window manager) could set it for all apps, or could go down to the shell's initialization (`.bashrc` and friends), it's unclear to me what would be the best.

Of course it doesn't help that there isn't a generic, desktop-independent preferred way of setting these variables.

**Comment by lanoxx** [comment]
I agree with @egmontkob, this is not something that tilda should fix. We would just be introducing yet another way to manage proxy settings in addition to the many different ways that different apps already support. If you want this to apply for all shell programs just set it in your `.bashrc`. Otherwise I would suggest to push for a desktop independent specification but this would be something the freedesktop.org would need to handle.
