### ISSUE TITLE
Tilda doesn't work with FreeBSD

### ISSUE THREAD

**Issue by rosorio** [lanoxx/tilda#337]
Hi,
Tilda stops working in the FreeBSD, everything around works (configuration
window, create tabs, roll up/down with F1) but the console don't accept inputs.
Even the prompt is not printed. This occurs with tilda 1.3.3 who works on the past
and tilda 1.4.1 I'm currently testing.

My guess, is that the problem comes from the dependencies. The current version
uses those libs :
        libgio-2.0.so.0
        libintl.so.8 
        libglib-2.0.so.0
        libgobject-2.0.so.0
        libX11.so.6
        libpango-1.0.so.0
        libgdk_pixbuf-2.0.so.0
        libgtk-3.so.0 
        libvte-2.91.so.0  (vte3-0.48.3)
        libconfuse.so.0 (libconfuse-2.7)

**Comment by voidplayer** [comment]
Im just an user like you, but i think current maintainer is quite busy and he doesnt run freebsd

Would you mind looking into what could be the a fix for this?

**Comment by cleberalves40** [comment]
*This is not a solution!*
1 - Over there I used keystroke CTRL + SHIFT + T, to open new tabs;
2 - If I need out of, reboot, shut down the system, close all tabs, because the previous setup will be lost.
It is boring, but works.
My wm is Fluxbox, I had tested with lumina, too. Just the same proceeding.
