### ISSUE TITLE
[bug] Gnome desktop crashes/restarts when tilda is killed by kill $tilda_pid

### ISSUE THREAD

**Issue by photonxp** [lanoxx/tilda#373]
OS:
Ubuntu 16
Debian 8.9

Package:
Package: tilda
Version: 1.3.1-1

How I reproduce the bug:
* Start tilda by clicking the launch icon
* grep to get the pid of tilda
* kill $tilda_pid
* Then Gnome desktop crashes and restarts automatically. It happens every time I do so.

Don't know how to reproduce the bug with `gdb tilda` when I can't get the tilda pid.
Tried to build Tilda but found the building process is out of my ability.

`sudo autoreconf --install`
`sudo ./configure --prefix=$prefix_path --enable-maintainer-flags`

> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether make supports nested variables... (cached) yes
> checking whether to enable maintainer-specific portions of Makefiles... yes
> checking for glib-mkenums... no
> **configure: error: Could not find a glib-mkenums in your PATH**

`dpkg -l |grep libglib2.0`
> ii  libglib2.0-0:amd64                         2.48.2-0ubuntu4.1                            amd64        GLib library of C routines
> ii  libglib2.0-bin                             2.48.2-0ubuntu4.1                            amd64        Programs for the GLib library
> ii  libglib2.0-data                            2.48.2-0ubuntu4.1                            all          Common files for GLib library

**Comment by byteSamurai** [comment]
Can you post a pstree before you kill tilda?

**Comment by lanoxx** [comment]
Documentation on how to build tilda is in [Hacking.md](https://github.com/lanoxx/tilda/blob/master/HACKING.md).

If you are missing glib-mkenum then you are probably missing `libglib2.0-dev-bin`, `libglib2.0-dev` depends on this and `libgtk-3-dev` in turn depends on `libglib2.0-dev` which is mentioned as a compile time dependency in Hacking.md.

When I kill tilda on my system it is closed just fine and I think its quite unlikely that killing tilda crashes your whole GNOME desktop. In any case you will need to provide some more detailed information if this is really cased by tilda so that its possible to reproduce this. I am closing this for now, if you can add more information on how to reproduce this please reopen.
