### ISSUE TITLE
Transparency setting has no effect in Cinnamon

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [lanoxx/tilda#383]
Cf.: #95; #221; #228; #343.

In short, it seems transparency is not working in many - all? - DEs.

Also, <super>-d hides Tilda and there seems no way to get Tilda back. She's gone! EDIT: the option 'set as desktop window' seems to fix that particular problem.

Linux Mint 19.1 Cinnamon
Tilda

**Comment by byteSamurai** [comment]
Well at least in Gnome it works perfectly. So it does not affect all DEs

**Comment by solacelost** [comment]
I believe you're encountering an issue with autostart, @LinuxOnTheDesktop . You don't explicitly say it, but I have personally had no problems with transparency _except_ when set to autostart, and the problem is the way in which Mutter starts up is asynchronous and the compositor isn't properly handling transparency very early on.

Change your autostart entry to include a 5 second delay, supposing this is your problem, and it should be resolved.

**Comment by LinuxOnTheDesktop** [comment]
solacelost, that is a very illuminating reply: it explains why I have had problems with some other programs (conky, rainlendar) when they are run on boot. Do you know whether the mutter bug is fixed upstream? Thanks. I won't comment on Tilda because I no longer use it.

**Comment by solacelost** [comment]
I'm no longer using Mutter, or Tilda even, so I'm not certain as I haven't been following/troubleshooting them.

I shifted to i3wm and lost the need for Tilda after that. :)

Good luck to you!
