### ISSUE TITLE
switch Keypress by Keydown

### ISSUE THREAD

**Issue by EdgardoArriagada** [lanoxx/tilda#400]
Hello!

Can you please consider switching keypress by Keydown? so it prevents the entire app crashing when you do Keyhold F1 (Pull Down Terminal) button...
I know almost nobody triggers a Keyhold on F1 in their daily basis, but it bugs my subconscious mind

gj for this amazing terminal, I just discovered it today
blessings!

**Comment by lanoxx** [comment]
I think by crashing you are referring to the bad match errors that sometimes occur during the toggle action. If thats the case then please know that those errors have been fixed in recent versions of tilda. If you can still reproduce those errors with the latest version of tilda then please reopen this bug.
