### ISSUE TITLE
Tilda searchbar does not respect dark themes

### ISSUE THREAD

**Issue by kanehekili** [lanoxx/tilda#437]
The background color of the searchbar is  white - always. As long as you're using a light/gray theme is doesn't hurt, but it looks weird with a dark theme.

GTK introspection shows that the background color has been defined locally for the box with ID=search. 
![image](https://user-images.githubusercontent.com/4390452/94861166-5c1c4100-0437-11eb-8b90-2941f8756610.png)

**Comment by lanoxx** [comment]
You are right, that has been defined here: https://github.com/lanoxx/tilda/blob/master/src/tilda.c#L533:

```
style = "#search{background:#fff;}";
```

I agree that this is not a suitable solution to handle dark themes.

**Comment by lanoxx** [comment]
Here is some background on this issue. The problem has actually been bugging me for many years, and the addition of the white background to the search box was just a poor work around for the issue. This workaround worked well for light themes but obviously fails for dark themes.

I spend some time on this today and finally found a solution which I believe works a bit better than the hard-coded CSS rule that we used before. I am closing this issue because I believe the change in commit 157e2b7 solves the problem. If not, then please reopen this issue with more details.

**Comment by kanehekili** [comment]
I've submitted bug reports on Arch and Ubuntu, to get it upstream. Thanks for your help

**Comment by lanoxx** [comment]
Not sure what you mean by "get it upstream". This project is the upstream project. The code is already in the master branch, but I have made a new release yet, so this will take some time to appear in Ubuntu.

**Comment by kanehekili** [comment]
My mistake. I've meant "downstream". Arch has already reacted, debian (surprise) not. Since I'm using Tilda on a daily base I'd like to thank you for your excellent work.
