### ISSUE TITLE
Tilda not catching keybinds out of focus in Ubuntu 21.04

### ISSUE THREAD

**Issue by LeNiglo** [lanoxx/tilda#457]
Hello,

I recently upgraded to Ubuntu 21.04 and Tilda just stopped behaving like it should.
The keybind is properly catched when tilda terminal is focused, but when out of focus, nothing.

Tested with ², ~, F1, Alt+B, same result.

Does anyone already had a similar issue and/or a way to make it work properly ?

Regards

**Comment by eugenioperea** [comment]
I have the same problem, also since updating to 21.04, but I've seen a slightly different effect: it depends on the app in focus. Tilda works fine with Chrome and its webapps, Thunderbird, and Telegram Desktop. It does not work with all other apps I've tried: Firefox, LibreOffice, RedNotebook, Files, or any Gnome app.

**Comment by Chofoteddy** [comment]
Seems to be a Wayland bug reported at 2013: https://bugs.launchpad.net/mutter/+bug/1244090.

**Comment by MrTransistorsChannel** [comment]
Same thing with my system. I think the it has to do something with the way Wayland handles hotkeys because the problem is only present when running a Wayland session. Also this happens to other programs like Guake terminal (which I`m currently using because of this bug) but with Guake you can just create a keybind in system preferences to perform "guake -t" command which toggles the visibility so I suggest adding something similar to Tilda in case there`s no way to fix this issue in a different way.

**Comment by lanoxx** [comment]
Related to #150 and #314. #407 added DBus support and allows you to register a global hotkey. For now you will have to compile from master until there is a new release.

**Comment by lanoxx** [comment]
To summarize this. This occurs only on Wayland sessions, if you keep using X11 sessions you are fine. On Wayland you will need to register a global hotkey, for example via Gnome Settings and invoke the new DBus interface of tilda to toggle the window.

**Comment by klausi** [comment]
Documented how to switch from Wayland to X11 in #462 , thanks for the hint!
