### ISSUE TITLE
Please create an AppData file for Tilda

### ISSUE THREAD

**Issue by hughsie** [lanoxx/tilda#98]
Please consider writing and installing an AppData file with the application description and some screenshots, else Tilda looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't.

See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by pik** [comment]
What is the status on this?

**Comment by lanoxx** [comment]
Hi Alex, Richard,

I did not have much time recently. If you want to write such a file and send me a pull request, then I will be happy to merge it. Please also include distribution infos (e.g. where does this file need to be installed). Otherwise this will have to wait until I can spare some time to work on tilda.

**Comment by lanoxx** [comment]
This was already merged, closing.
